-- liquibase formatted sql

-- changeset 15925:1720412366800-1
CREATE TABLE book
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255),
    author     VARCHAR(255),
    library_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

-- changeset 15925:1720412366800-2
CREATE TABLE library
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_library PRIMARY KEY (id)
);

-- changeset 15925:1720412366800-3
ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_LIBRARY FOREIGN KEY (library_id) REFERENCES library (id);


